"""身份用例族(application/identity)。

W2-B 由 services/identity.py 搬入: 用户管理/窗口会话/登录限速/认证审计/
应用级设置的全部编排(用例顶层函数拥有事务提交, 数据读写只经
identity/project/audit 域公开门面, 不导入 iesplan.models.*)。

输入规则、身份错误与身份状态归 identity 域所有(定义见
iesplan.identity 门面与 iesplan.identity.contracts); 本包负责对外重导出
身份用例、审计与项目编排能力，保持应用层调用方使用稳定门面。
"""

from iesplan.application.identity.service import (
    EMAIL_RE,
    KEY_REGISTRATION_ENABLED,
    USERNAME_RE,
    as_utc,
    authenticate,
    change_password,
    confirm_takeover,
    create_user,
    create_window_session,
    deactivate_user,
    delete_user,
    ensure_role,
    expire_session,
    expire_sessions,
    extend_session,
    get_active_password_credential,
    get_app_setting,
    get_session_by_token,
    get_user_by_id,
    get_user_by_username,
    has_role,
    list_users,
    owned_project_ids,
    preview_user_delete,
    reactivate_user,
    record_auth_event,
    registration_enabled,
    reset_password,
    revoke_all_user_sessions,
    revoke_other_sessions,
    revoke_session,
    revoke_session_after_credential_change,
    set_app_setting,
    set_registration_enabled,
    touch_session,
    user_roles,
    utcnow,
    verify_delete_confirm_token,
)
from iesplan.application.identity.views import UserView, user_view, user_views
from iesplan.core.security import token_hash
from iesplan.identity import (
    LOCKOUT_SECONDS,
    MAX_LOGIN_FAILURES,
    ROLE_ADMIN,
    ROLE_ENGINEER,
    reset_login_rate_limit,
)
from iesplan.identity.contracts import (
    AuthError,
    AuthRequiredError,
    BadOldPasswordError,
    BadRequestError,
    DeleteConfirmRequiredError,
    ForcePasswordChangeError,
    LockedError,
    LoginFailedError,
    RegistrationDisabledError,
    SamePasswordError,
    SessionInvalidError,
    UserDisabledError,
    WeakPasswordError,
)

__all__ = [
    "EMAIL_RE",
    "KEY_REGISTRATION_ENABLED",
    "LOCKOUT_SECONDS",
    "MAX_LOGIN_FAILURES",
    "ROLE_ADMIN",
    "ROLE_ENGINEER",
    "USERNAME_RE",
    "AuthError",
    "AuthRequiredError",
    "BadOldPasswordError",
    "BadRequestError",
    "DeleteConfirmRequiredError",
    "ForcePasswordChangeError",
    "LockedError",
    "LoginFailedError",
    "RegistrationDisabledError",
    "SamePasswordError",
    "SessionInvalidError",
    "UserDisabledError",
    "UserView",
    "WeakPasswordError",
    "as_utc",
    "authenticate",
    "change_password",
    "confirm_takeover",
    "create_user",
    "create_window_session",
    "deactivate_user",
    "delete_user",
    "ensure_role",
    "expire_session",
    "expire_sessions",
    "extend_session",
    "get_active_password_credential",
    "get_app_setting",
    "get_session_by_token",
    "get_user_by_id",
    "get_user_by_username",
    "has_role",
    "list_users",
    "owned_project_ids",
    "preview_user_delete",
    "reactivate_user",
    "record_auth_event",
    "registration_enabled",
    "reset_login_rate_limit",
    "reset_password",
    "revoke_all_user_sessions",
    "revoke_other_sessions",
    "revoke_session",
    "revoke_session_after_credential_change",
    "set_app_setting",
    "set_registration_enabled",
    "token_hash",
    "touch_session",
    "user_roles",
    "user_view",
    "user_views",
    "utcnow",
    "verify_delete_confirm_token",
]
